apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lVQ1dzWkhIMlV5eEUwZ1Z6T0t5bTl3OVI1UVdFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pNVEkzTGpBdU1DNHhNQjRYRFRFNU1EWXhNakEzTVRVMU0xb1hEVFEyTVRBeQpPREEzTVRVMU0xb3dGREVTTUJBR0ExVUVBd3dKTVRJM0xqQXVNQzR4TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBczIrZ1M0b1p2SWpRQTBucU5xdndUZmZsdlFZQWluck5CT3JnbnhmMmNCL2UKT05BNldnZ1oySXAvOGtaYlM3VzZ2SkVYVlBEM1YwOEZlOXhXWjlPbnM4Yml3RG9XNUVSaTFTTmlXT1ZHZG93agpkLzJFTUhGWmlHNGxqMDZRemFrdGhWWkp6YUVXd3dDSmVxTTl2R1pUZTBaRjA2ZzJWRkZPd3RTcFM3ZnVqc3hHCnJWTlBlMWdjNDBKQUU2VjRuL2oxSU9HRkR3aXNhVThxUGRqbzNOdkpsR2RjdmlodUNDTU9ydnFSalNPVyt2NFYKd1lrQnhmYmVLZHhOVStNNFNraUU3SDg2bytpNFhCWVB0Vyszd21kK3E0TEFRSHhxaktnZmcralVhWE5xK1ZNQQo1TXV6WWFqTUx6TFpzVStRRFA4c2U2YTZpQU5aYjdHM3VVVEkwM04ySHdJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVHK0NJU2FSbStUb1VXNUkvQ09sclgyQ2p4NDB3SHdZRFZSMGpCQmd3Rm9BVUcrQ0lTYVJtK1RvVVc1SS8KQ09sclgyQ2p4NDB3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVDBOcAoxQm1sTG4ydmgybzJFNTA4TEFXTGJoYkpQZWJ3bFROZGJTOGI5a0lWemVseVl5SWtubXluZ1c2cUN2L0dRQ2gzCjB3TmRvZHRaWUVZOUN1dVFCWVZEbnd3blduaXlCN0NHbnBwTEFCV041c2xjUHRxMUdLUnVhT1RVUnBRWDZDdVcKNjJMRElSTnFMQW1VR0N0cFQ5V2xRRm1ITzVNZFU1NG4xQWhhYlJsekFHcGNjb1hWcGRDZ21jRjYyVkRJSVlYSgpUT0ZjdVhPbmlOdFNWR2NvdkxVZ1ROUEd1MmEzTFZFYlk5Q2VIeERXZG14UHdyTEFXeFlkSXFic1Z2a0JreHBFCnd6aWxuSTF0aGlaQWIxVjQ3OU4yZnZOa2M1dXhNNVcxSGx0QmdBVHZiVUZxZDVzNk8wb1hLRloydHl2KzhqZlIKbm44K0FvMmg1bjFGZEVFQ1dnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://54.171.47.13:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password: RTFRUk9GL3VRZ2diZlF4cGdMbzR0WkxHOVQvTnAvbEFWRjk5SFJ3WklRWT0K
